#! /usr/bin/python


import os,sys, subprocess

if len( sys.argv) != 2:
	print("Accept one virtenv paramter only.")
	exit(1)

filepath="bin/activate"
target="%s"%sys.argv[1]
try:
        if os.path.exists( target ):
            os.chdir( target)

	if os.path.exists(filepath):
		subprocess.call(["bash --rcfile %s"%filepath ], shell=True )
	else:
		raise
except:
	print("%s isn't a virtenv."%(sys.argv[1]))
	exit(1)
